### ISSUE TITLE
Fix in-slide terminals not connecting

### ISSUE THREAD

**Issue by fin-ger** [fin-ger/git-talk#2]
We have to migrate the in-slide terminals from an iframe approach to a single-websocket direct approach which requires altering of the backend. This is because it is only allowed to open 2 websockets at once on one domain in this browser.

**Comment by martin31821** [comment]
Updated angular to v7 in #8

**Comment by fin-ger** [comment]
We will need a deployment for the terminal containers. I would suggest using docker-compose for this.
